.TH SecProv 3   "API Reference"
.SH NAME
CheckProcess
.SH DESCRIPTION
This function reports if a process still is active.
.SH SYNOPSIS
.B #include <plf_proc.h>
.sp
.B int CheckProcess(pid);
.SH PARAMETERS
.TP
.B int pid
Process id.
.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.PP
