.TH SecProv 3   "API Reference"
.SH NAME
NBaseName
.SH DESCRIPTION
This function returns the leaf component of a pathname.
.SH SYNOPSIS
.B #include <dir.h>
.sp
.B char* NBaseName(path);
.SH PARAMETERS
.TP
.B const char * path
The complete pathname.
.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR NDirOpen(3)
.BR NDirRead(3)
.BR NDirClose(3)
.BR NDirResolveLink(3)
.BR NDirRemove(3)
.PP
