.TH SecProv 3   "API Reference"
.SH NAME
NDirClose
.SH DESCRIPTION
This function is a Windows-compatible version of closedir.
.SH SYNOPSIS
.B #include <dir.h>
.sp
.B int NDirClose(hdir);
.SH PARAMETERS
.TP
.B HDIRECTORY hdir
Pointer to the directory handle.
.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR NDirOpen(3)
.BR NDirRead(3)
.BR NDirResolveLink(3)
.BR NDirRemove(3)
.BR NBaseName(3)
.PP
