.TH SecProv 3   "API Reference"
.SH NAME
NDldGetExtension
.SH DESCRIPTION
Returns file extension for shared libraries on this platform.
.SH SYNOPSIS
.B #include <dynload.h>
.sp
.B char* NDldGetExtension(void);
.SH PARAMETERS
.TP
.B void void

.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR NDldLoadLibrary(3)
.BR NDldUnloadLibrary(3)
.BR NDldLoadSymbol(3)
.BR NDldLoadFunc(3)
.BR NDldGetError(3)
.PP
