.TH SecProv 3   "API Reference"
.SH NAME
NGetOptind
.SH DESCRIPTION
This function returns the index of the next argv entry to be processed.
.SH SYNOPSIS
.B #include <ngetopt.h>
.sp
.B int NGetOptind(void);
.SH PARAMETERS
.TP
.B void void

.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR NGetOpt(3)
.BR NGetOptarg(3)
.PP
