.TH SecProv 3   "API Reference"
.SH NAME
NGetOptarg
.SH DESCRIPTION
This function returns the current optarg value.
.SH SYNOPSIS
.B #include <ngetopt.h>
.sp
.B char* NGetOptarg(void);
.SH PARAMETERS
.TP
.B void void

.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR NGetOpt(3)
.BR NGetOptind(3)
.PP
