.TH SecProv 3   "API Reference"
.SH NAME
NMemFree
.SH DESCRIPTION
This function deallocates a buffer allocated by one of the functions
.SH SYNOPSIS
.B #include <memory.h>
.sp
.B void NMemFree(pMemBlk);
.SH PARAMETERS
.TP
.B void * pMemBlk
Buffer to deallocate.
.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR NMemPool(3)
.BR NMemAlloc(3)
.BR NMemAlloc_align(3)
.BR NMemRealloc(3)
.BR NMemFree_align(3)
.BR NMemCopy(3)
.BR NMemMove(3)
.BR NMemSet(3)
.BR NMemCmp(3)
.BR NMemReadable(3)
.BR NMemWriteable(3)
.BR NStrDup(3)
.BR NMemDup(3)
.BR NMemAddMallocStat(3)
.BR NMemAddFreeStat(3)
.BR NMemPrintStats(3)
.PP
