.TH SecProv 3   "API Reference"
.SH NAME
NMemAlloc_align
.SH DESCRIPTION
This function allocates a new memory buffer, where all bytes are initialized to 0. The align argument must be a multiple of 2
.SH SYNOPSIS
.B #include <memory.h>
.sp
.B void* NMemAlloc_align(bytes, align);
.SH PARAMETERS
.TP
.B size_t bytes
The number of bytes to allocate.
.TP
.B size_t align
to place the memory
.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR NMemPool(3)
.BR NMemAlloc(3)
.BR NMemRealloc(3)
.BR NMemFree(3)
.BR NMemFree_align(3)
.BR NMemCopy(3)
.BR NMemMove(3)
.BR NMemSet(3)
.BR NMemCmp(3)
.BR NMemReadable(3)
.BR NMemWriteable(3)
.BR NStrDup(3)
.BR NMemDup(3)
.BR NMemAddMallocStat(3)
.BR NMemAddFreeStat(3)
.BR NMemPrintStats(3)
.PP
