.TH SecProv 3   "API Reference"
.SH NAME
NMemPrintStats
.SH DESCRIPTION
Prints number of NMemAlloc,NMemFree done and memory used using trace_d if MEM_DBG is defined. It also lists the start addresses to currently allocated memory blocks.
.SH SYNOPSIS
.B #include <memory.h>
.sp
.B int NMemPrintStats(void);
.SH PARAMETERS
.TP
.B void void

.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR NMemPool(3)
.BR NMemAlloc(3)
.BR NMemAlloc_align(3)
.BR NMemRealloc(3)
.BR NMemFree(3)
.BR NMemFree_align(3)
.BR NMemCopy(3)
.BR NMemMove(3)
.BR NMemSet(3)
.BR NMemCmp(3)
.BR NMemReadable(3)
.BR NMemWriteable(3)
.BR NStrDup(3)
.BR NMemDup(3)
.BR NMemAddMallocStat(3)
.BR NMemAddFreeStat(3)
.PP
