.TH SecProv 3   "API Reference"
.SH NAME
NThreadExit
.SH DESCRIPTION
This function terminates a thread.
.SH SYNOPSIS
.B #include <plf_proc.h>
.sp
.B void NThreadExit(val_ptr);
.SH PARAMETERS
.TP
.B void * val_ptr
Pointer to exit return status.
.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR NThreadCreate(3)
.BR NThreadDetach(3)
.PP
