.TH SecProv 3   "API Reference"
.SH NAME
NThreadDetach
.SH DESCRIPTION
This function makes the thread independent of the main thread.
.SH SYNOPSIS
.B #include <plf_proc.h>
.sp
.B int NThreadDetach(thread);
.SH PARAMETERS
.TP
.B void * thread
Handle to thread to detach.
.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR NThreadCreate(3)
.BR NThreadExit(3)
.PP
