.TH SecProv 3   "API Reference"
.SH NAME
plf_load_file
.SH DESCRIPTION
This function provides simple handling
This functions reads a file into a memory buffer allocated by NMemAlloc (malloc).
.SH SYNOPSIS
.B #include <file.h>
.sp
.B file_io plf_load_file();
.SH PARAMETERS
.SH RETURN VALUES
.TP
.B pointer
No brief for pointer
.TP
.B NULL
No brief for NULL
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.PP
