.TH SecProv 3   "API Reference"
.SH NAME
target_reboot
.SH DESCRIPTION
Immidiate reboot of target base operating system
.SH SYNOPSIS
.B #include <system.h>
.sp
.B void target_reboot(void);
.SH PARAMETERS
.TP
.B void void

.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR target_identity(3)
.PP
