.TH SecProv 3   "API Reference"
.SH NAME
udelay
.SH DESCRIPTION
No description
.SH SYNOPSIS
.B #include <timer.h>
.sp
.B void udelay(useconds);
.SH PARAMETERS
.TP
.B int useconds
This function sleeps specified number of microseconds
.SH RETURN VALUES
.SH COPYRIGHT
 \(co Oniteo 2007-2008
.SH SEE ALSO
.BR mdelay(3)
.PP
