#########################
#
## Copyright Oniteo 2007-2008 
#
##########################


PREFIX ?= /home/hans/haspoc/build


build: 

install:


clean: 

prepare:
	mkdir -p       $(DESTDIR)$(PREFIX)/include
	cp bios_low.h       $(DESTDIR)$(PREFIX)/include
	# cp arm64_v8_dev-1.1/bl1/aarch64/bl1_entrypoint.S $(DESTDIR)$(PREFIX)/include
	# cp arm64_v8_dev-1.1/bl1/aarch64/bl1_exceptions.S $(DESTDIR)$(PREFIX)/include
	# cp bl1_plat_setup.c $(DESTDIR)$(PREFIX)/include
	# cp bl2_plat_setup.c $(DESTDIR)$(PREFIX)/include

