#########################
#
## Copyright Oniteo 2007-2008 
#
##########################


CC_TOP ?= /home/hans/sb


build: 

install:


clean: 
	rm -f gcc-linaro-aarch64-none-elf-4.9-2014.07_linux.tar.gz

prepare:
	mkdir -p       $(CC_TOP)/tools/crosscompiler
	( cd $(CC_TOP)/tools/crosscompiler && tar xzf $(CC_TOP)/src/linaro/gcc-linaro-aarch64-none-elf-4.9-2014.07_linux.tar.gz )

