/*
	Input root_pk.pem 
	Generated by hsbf_signer

	Subject: /CN=t2data.com/emailAddress=info@t2data.com/O=T2Data/OU=RD/ST=Stockholm/C=SE
	size of n = 256 , e = 3

	The content of root_pk_hash_value array,  
	is calculated by hashing the e and n  exponent for a RSA key
	Prior to use of the actual ROOT_PK key the hash must match

	The trust chain depends on how the root_pk_hash_value is stored
*/

#define  ROOT_PK_HASH_TYPE SHA256_BIN

#define  ROOT_PK_HASH_SIZE 32 

static const char root_pk_hash_value[] = {
	0xf4,0xf4,0x1e,0xf4,0x49,0x20,0xbb,0x8f,
	0xc0,0x88,0xae,0x51,0x2f,0xed,0x4b,0x1,
	0x27,0x8,0x8d,0xf5,0xe0,0xb8,0x24,0xc3,
	0xb5,0xc0,0xd,0x16,0x4b,0x65,0x6a,0xbb
	};
