#########################
#
## Copyright Oniteo 2007-2008 
#
##########################


PREFIX ?= /home/hans/haspoc/build


build: 

install:


clean: 

prepare:
	mkdir -p       $(DESTDIR_STATE)$(PREFIX)/include
	cp bios_memory.h       $(DESTDIR_STATE)$(PREFIX)/include

