#########################
#
## Copyright Oniteo 2007-2008 
#
##########################


PREFIX ?= /home/hans/haspoc/build


build: 

install:


clean: 

prepare:
	mkdir -p              $(DESTDIR_STATE)$(PREFIX)/bios/include/plf
	cp plf/safestr.h      $(DESTDIR_STATE)$(PREFIX)/bios/include/plf
	cp plf/platform.h     $(DESTDIR_STATE)$(PREFIX)/bios/include/plf
	cp plf/optimized.h    $(DESTDIR_STATE)$(PREFIX)/bios/include/plf
	cp plf/io.h           $(DESTDIR_STATE)$(PREFIX)/bios/include/plf
	cp plf/timer.h        $(DESTDIR_STATE)$(PREFIX)/bios/include/plf
	cp misc.h             $(DESTDIR_STATE)$(PREFIX)/bios/include/plf
	cp endian.h           $(DESTDIR_STATE)$(PREFIX)/bios/include/plf
	cp arch.h             $(DESTDIR_STATE)$(PREFIX)/bios/include/plf


